title: nemo
description: a CLI tool for hiding files
theme: minima
header_pages:
  - overall-plan.md
  - user-interface.md
  - architecture.md
  - work-breakdown.md
  - techniques/overview.md
  - file-systems/overview.md
